### ISSUE TITLE
nc: getaddrinfo failed: Temporary failure in name resolution

### ISSUE THREAD

**Issue by rx1432** [yacovm/fabricDeployment#2]
Hi, everything is working fine but when i execute deploy.sh , and it reaches to "starting orderer" it gives this error.

**waiting for orderer and peers to be online
nc: getaddrinfo failed: Temporary failure in name resolution**
I have completed all the prerequisites. e.g. password less ssh, sudo, local repo etc.
Is it related to dns ?

**Comment by yacovm** [comment]
Seems so... do you want to ping me in rocket.chat ? https://chat.hyperledger.org

**Comment by rx1432** [comment]
Yes sure. I am on it.
